---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(flexdashboard)
library(crosstalk)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(RColorBrewer)
library(plotly)
library(sf)
library(dplyr)
library(tigris)
library(p8105.datasets)


data(rest_inspec)

rest_inspec = 
  rest_inspec |> 
  janitor::clean_names() |>
  select(boro, zipcode, cuisine_description, score, grade, critical_flag, inspection_date) |>
  drop_na(score, grade) |>
  mutate(cuisine_description = recode(cuisine_description, "Café/Coffee/Tea" = "Cafe/Coffee/Tea")) |>
  mutate(boro = recode(boro, "BRONX" = "Bronx",
                            "BROOKLYN" = "Brooklyn",
                            "MANHATTAN" = "Manhattan",
                            "QUEENS" = "Queens",
                            "STATEN ISLAND" = "Staten Island")) |>
  sample_n(1000)



# Chart A Data
avg_scores_by_zip <- rest_inspec %>%
  group_by(zipcode) %>%
  summarize(avg_score = mean(score, na.rm = TRUE)) %>%
  mutate(zipcode = as.character(zipcode))

## Original Work for Map
# Get NY ZIP code shapes for 2010 (only available year) and filter to NYC 
nyc_zip_shapes <- zctas(year = 2010, state = "NY") %>%
  filter(ZCTA5CE10 %in% avg_scores_by_zip$zipcode)

# Transform to match map projection and calculate centroids
nyc_zip_shapes <- st_transform(nyc_zip_shapes, crs = 4326)
nyc_zip_centroids <- st_centroid(nyc_zip_shapes)

# Extract centroid coords and merge with ZIP code data
nyc_zip_centroids <- nyc_zip_centroids %>%
  st_coordinates() %>%
  as.data.frame() %>%
  rename(long = X, lat = Y) %>%
  bind_cols(nyc_zip_shapes %>% st_drop_geometry()) %>%
  rename(zipcode = ZCTA5CE10) %>%
  inner_join(avg_scores_by_zip, by = "zipcode")

```

Column {data-width=650}
-------------------------------------

### Chart A

```{r charta, warning = FALSE, echo = FALSE, message = FALSE}

charta <- nyc_zip_centroids %>%
  plot_ly(lat = ~lat, lon = ~long,
        type = 'scattermapbox', mode = 'markers',
        marker = list(
          size = 8,
          opacity = 0.7,
          color = ~avg_score,
          colorscale = 'PuRd',
          colorbar = list(title = "Avg Score")),
        text = ~paste("ZIP Code:", zipcode, "<br>Avg Score:", round(avg_score, 2)),
        hoverinfo = 'text')
charta <- charta %>%
  layout(mapbox = list(style = 'carto-positron', zoom = 9,
                  center = list(lat = 40.730610, lon = -73.935242)))
charta

```

Column {data-width=350}
-------------------------------------

### Chart B

```{r chartb, warning = FALSE, echo = FALSE, message = FALSE}

chartb <- rest_inspec %>%
  plot_ly(y = ~score, color = ~boro, type = 'box', colors = 'Oranges', 
          text = ~str_c("Borough: ", boro, "\nScore: ", score),
          hoverinfo = "text") 
chartb <- chartb %>%
  layout(title = "Distribution of Inspection Scores by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Inspection Score"))
chartb 

```

### Chart C

```{r chartc, warning = FALSE, echo = FALSE, message = FALSE}

chartc <- rest_inspec %>%  
  count(boro) |>
  mutate(boro = fct_reorder(boro, n)) |>
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "Oranges", 
          text = ~str_c("Borough: ", boro, "\nCount: ", n),
          hoverinfo = "text") 
chartc <- chartc %>%
  layout(title = "Count of Violations by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Violation Count"))
chartc

```
